-- MySQL Script generated by MySQL Workbench
-- Mon Oct  9 22:11:57 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema eternamente
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema eternamente
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `eternamente` DEFAULT CHARACTER SET utf8 ;
USE `eternamente` ;

-- -----------------------------------------------------
-- Table `eternamente`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eternamente`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(60) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `birthday` DATE NOT NULL,
  `picture` LONGTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eternamente`.`board`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eternamente`.`board` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eternamente`.`list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eternamente`.`list` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `color` VARCHAR(45) NULL,
  `board_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_list_board1_idx` (`board_id` ASC),
  CONSTRAINT `fk_list_board1`
    FOREIGN KEY (`board_id`)
    REFERENCES `eternamente`.`board` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eternamente`.`task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eternamente`.`task` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `description` LONGTEXT NULL,
  `date` DATE NULL,
  `color` VARCHAR(45) NULL,
  `completed` TINYINT NOT NULL,
  `help` TINYINT NOT NULL,
  `helptext` LONGTEXT NULL,
  `list_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_task_list1_idx` (`list_id` ASC),
  CONSTRAINT `fk_task_list1`
    FOREIGN KEY (`list_id`)
    REFERENCES `eternamente`.`list` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eternamente`.`label`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eternamente`.`label` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `color` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eternamente`.`task-label`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eternamente`.`task-label` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `task_id` INT NOT NULL,
  `label_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_task-label_task_idx` (`task_id` ASC),
  INDEX `fk_task-label_label1_idx` (`label_id` ASC),
  CONSTRAINT `fk_task-label_task`
    FOREIGN KEY (`task_id`)
    REFERENCES `eternamente`.`task` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_task-label_label1`
    FOREIGN KEY (`label_id`)
    REFERENCES `eternamente`.`label` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eternamente`.`usuario-board`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eternamente`.`usuario-board` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NOT NULL,
  `board_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuario-task_usuario1_idx` (`usuario_id` ASC),
  INDEX `fk_usuario-task_board1_idx` (`board_id` ASC),
  CONSTRAINT `fk_usuario-task_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `eternamente`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario-task_board1`
    FOREIGN KEY (`board_id`)
    REFERENCES `eternamente`.`board` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
